version: '3.8'

services:
  api:
    build:
      context: ./api-interface
      dockerfile: Dockerfile
    container_name: api
    env_file:
      - ./api-interface/.env
    environment:
      - GRPC_ADDRESS=converter:50051
      - PORT=8000
    depends_on: 
      - converter
    networks:
      - backend
    ports:
      - 8000:8000

  converter:
    build:
      context: ./converter
      dockerfile: Dockerfile
    container_name: converter
    env_file:
      - ./converter/.env
    environment:
      - PORT=50051
    networks:
      - backend
    ports:
      - 50051:50051
    restart: on-failure

networks:
  backend:
    driver: bridge
