version: '3.8'

services:
  api:
    build:
      context: ./api-interface
      dockerfile: Dockerfile
    env_file:
      - ./api-interface/.env
    depends_on: 
      - converter
    networks:
      - backend
    ports:
      - 8000:8000
  converter:
    build:
      context: ./converter
      dockerfile: Dockerfile
    env_file:
      - ./converter/.env
    networks:
      - backend
    ports:
      - 50051:50051

networks:
  backend:
